server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  application:
    name: iphone-web-be
  web:
    locale: vi_VN
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/iphone-service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 360000

